# Python for Data Analysis - Workbook

### Preliminaries

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('../Memorial Day DS Project/us_only_v1.0.csv')

## Basics: Built-in Data Structures, Functions, and Files

### Data Structures and sequences

#### Tuples

In [8]:
# a tup is a fixed length, immutable sequence of python obj's. They can be created like this:

tup = 4,5,6

In [9]:
# This one is nested
nested_tup = (4,5,6),(7,8)

In [11]:
# Any sequence or iterator (more on that later) can be converted to a tuple like this:

tuple([4,4,2])
tuple('string')

('s', 't', 'r', 'i', 'n', 'g')

In [12]:
# Just like any C, C++, or aa array, tuples can be accessed with thte [] notation
tup[0]

4

In [15]:
# You can concatenate tuples using the '+' symbol to produce longer tuples
tup + nested_tup

(4, 5, 6, (4, 5, 6), (7, 8))

In [16]:
# But using the '*' character ('*' means multiply) instead of the '+' character has the
# effect of creating that many copies of the tuple

tup * 4

(4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6)

In [17]:
# Replicate a swap function as in e.g. C

tup = [4,5,6]
a, b = 1, 2

In [21]:
# Common use for variable unpacking is iterating over sequences or lists

seq = [1,2,3], [4,5,6], [7,8,9]

for a,b,c in seq:
    print('a={0} b={1}, c={2}'.format(a,b,c))

a=1 b=2, c=3
a=4 b=5, c=6
a=7 b=8, c=9


In [22]:
# Count the number of occurences of a particular value in a list

a = (1,2,2,2,3,4,2)
a.count(2)

4

#### Lists

In [23]:
# List is variable length and contents can be modified in-place
# Defined using square brackets
# Equivalent to Javascript Array

In [24]:
# List function is commonly used in data processing as a way to create an iterator expression

gen = range(10)

In [25]:
gen

range(0, 10)

In [27]:
# Now we have a list from 0 - 9 (10 values)

list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
ex_list = ['foo', 'bar', 'baz']

In [35]:
# Can append or insert elements
ex_list.append('bow')

In [36]:
# Note: inserting/popping elements in a list is computationally expensive
ex_list.insert(0, 'dog')
ex_list

['dog', 'foo', 'bar', 'baz', 'bow']

In [37]:
ex_list.pop(0)
ex_list

['foo', 'bar', 'baz', 'bow']

In [38]:
# Or remove by value
ex_list.remove('baz')
ex_list

['foo', 'bar', 'bow']

In [42]:
# Check to see if a value is included in a specific list
'foo' in ex_list

True

In [43]:
'foo' not in ex_list

False

In [45]:
# Concatenation (expensive)

ex_list2 = ['dog', 'cat', 'mouse']
ex_list + ex_list2

['foo', 'bar', 'bow', 'dog', 'cat', 'mouse']

In [47]:
# Extension (cheaper)

ex_list.extend(ex_list2)
ex_list

['foo', 'bar', 'bow', 'dog', 'cat', 'mouse', 'dog', 'cat', 'mouse']

In [49]:
# Sorting lists

a = [3,4,1]
a.sort()
a

[1, 3, 4]

In [51]:
# Can pass in different keys, or functions that produce a value to search the objects

ex_list.sort(key=len)
ex_list

['foo', 'bar', 'bow', 'dog', 'cat', 'dog', 'cat', 'mouse', 'mouse']

##### Binary Search

In [62]:
# Binary search is implemented through the native "bisect" module

import bisect
c = [1,2,2,2,3,4,7]

In [63]:
bisect.bisect(c,2)

4

In [64]:
bisect.bisect(c,7)

7

In [65]:
# Inserting an element
# Note...list has to be sorted first!

bisect.insort(c,6)
c

[1, 2, 2, 2, 3, 4, 6, 7]

##### Slicing a List

In [66]:
# Slicing - basic form is start:stop to the indexing operator

seq = [7,2,3,7,5,6,0,1]
seq[1:5]

[2, 3, 7, 5]

In [67]:
# Can also assign with a sequence

seq[3:4] = [7,8]
seq

[7, 2, 3, 7, 8, 5, 6, 0, 1]

In [68]:
# Use negative indices to slice the sequence relative to the end

seq[-4:]

[5, 6, 0, 1]

In [69]:
seq[4:]

[8, 5, 6, 0, 1]

In [72]:
# Step size can be defined after a second colon, as below
seq[1:8:2]

[2, 7, 5, 0]

In [73]:
# Here's a handy way to reverse a list

seq[::-1]

[1, 0, 6, 5, 8, 7, 3, 2, 7]

##### Built in Sequence Functions

In [79]:
# Keep track of index of current item when enumerating over a list/dict

# Hard Way:

collection = [1,2,3]

i = 0
print('Hard Way\n')
for item in collection:
    print(item)
    i += 1

# Easy Way

print('\nEasy Way\n')
for i, value in enumerate(collection):
    print(item)

Hard Way

1
2
3

Easy Way

3
3
3


In [128]:
# Example - create some dict that is a mapping between two lists

some_list = ['foo', 'bar', 'baz']
mapping = {}

for i,v in enumerate(some_list):
    mapping[i] = v
    
print(mapping)

# Really easy way to make a dictionary
print(dict(mapping))

{0: 'foo', 1: 'bar', 2: 'baz'}
{0: 'foo', 1: 'bar', 2: 'baz'}


In [85]:
# Sorting

sorted([5,2,1,12,2])

[1, 2, 2, 5, 12]

In [86]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [89]:
# Zipping

seq1 = ['foo', 'bar', 'baz']
seq2 = ['dog', 'cat', 'three']

zipped = zip(seq1, seq2)
list(zipped)

[('foo', 'dog'), ('bar', 'cat'), ('baz', 'three')]

In [92]:
# Combining zip and enumerate for ultimate pythonism


seq1 = ['foo', 'bar', 'baz']
seq2 = ['dog', 'cat', 'three']

for i, (a,b) in enumerate(zip(seq1, seq2)):
    print('{0}: {1}, {2}'.format(i, a, b))

0: foo, dog
1: bar, cat
2: baz, three


In [108]:
# Unzip in a hacky way using '*'

pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'),('Schilling', 'Curt')]
first_names, last_names = zip(*pitchers)
first_names

('Nolan', 'Roger', 'Schilling')

In [112]:
# The above uses the '*' operator to 'unpack' the list. See below example

a,*b = pitchers
print(a)
print(b)

('Nolan', 'Ryan')
[('Roger', 'Clemens'), ('Schilling', 'Curt')]


#### Dicts (Also called key-value pairs or hashmaps)

In [122]:
ex_dict = {'a': 'some value', 'b': [1, 2, 3, 4]}

In [123]:
# Access dict item
ex_dict['a']

'some value'

In [124]:
# Replace item
ex_dict['b'] = [5, 6, 7, 8]
print(ex_dict)

{'a': 'some value', 'b': [5, 6, 7, 8]}


In [125]:
# Add item
ex_dict['fish'] = 'red'
print(ex_dict)

{'a': 'some value', 'b': [5, 6, 7, 8], 'fish': 'red'}


In [126]:
# Check for a key
'b' in ex_dict

True

In [127]:
# Two ways to delete: del which deletes the k/v or pop which returns the value and deletes key

del ex_dict['b']
print(ex_dict.pop('a'))

some value


In [135]:
# Keys and values
print(list(ex_dict.keys()))
print(list(ex_dict.values()))

['fish']
['red']


##### Merging two dicts

In [138]:
d1 = {'red': 1, 'blue': 2}
d2 = {'green': 3, 'purple': 4}
d1.update(d2)
print(d1)

# Note: changes in place

{'red': 1, 'blue': 2, 'green': 3, 'purple': 4}


#### Creating dicts from sequences

In [143]:
# dict is essentially a collection of 2-tuples
# Simple way to create a dict out of two lists

key_list = ['dog', 'cat', 'rabbit']
value_list = [1,2,3]

mapping = {}
for key, value in zip(key_list, value_list):
    mapping[key] = value
    
mapping

{'dog': 1, 'cat': 2, 'rabbit': 3}

##### Setting default values

In [147]:
# Hard way:

if key in some_dict:
    value = some_dict[key]
else:
    value = default

In [151]:
# can replace with get method (or pop):

ex_dict = {'dog':1, 'cat':2}
default = 3
print(ex_dict.get('dog', default))
print(ex_dict.get('baz', default))

1
3


#### Sets

A set is an unordered collection of unique elements

In [152]:
s1 = set([2,3,2,4,1,4,2,1,6])
print(s1)

{1, 2, 3, 4, 6}


In [154]:
# another way to create sets
s2 = {5,6,7,8}

In [156]:
# Supports all the mathetmatical set operations

s1.intersection(s2)

{6}

In [161]:
s1.union(s2)

# or

s1 | s2

{1, 2, 3, 4, 5, 6, 7, 8}

In [162]:
s1.difference(s2)

# or

s1 - s2

{1, 2, 3, 4}

In [163]:
s2.difference(s1)

# or

s2 - s1

{5, 7, 8}

In [164]:
s1.symmetric_difference(s2)

# or

s1 ^ s2

{1, 2, 3, 4, 5, 7, 8}

In [167]:
s1.issubset(s2)

# or

s1 <= s2

False

In [168]:
s1.issuperset(s2)

# or

s1 >= s2

False

In [169]:
# Plus many others

### List/Set/Dict Comprehension

##### List Comprehension

In [174]:
# List comprehension replaces this -->

# result = []
# for val in collection:
#     if condition:
#         result.append(expr)
        
# ...with this -->

# [expr for val in collection if condition]

In [186]:
# Example of list comprehension:

strings = ['a', 'as', 'bat', 'car', 'dove']
[x.upper() for x in strings if len(x) > 2]

# Note that the output is a list

['BAT', 'CAR', 'DOVE']

In [192]:
# Can also do nested list comprehensions

name_list = [['John', 'Emily', 'Valerie', 'Mickels'], ['Maria', 'Juan', 'Pilar', 'Steven']]

# HARD WAY

names_of_interest = []
for names in name_list:
    double_e = [name for name in names if name.count('e') >= 2]
    names_of_interest.extend(double_e)

print(names_of_interest)

# EASY WAY

result = [name for names in name_list for name in names if name.count('e') >= 2]
print(result)

['Valerie', 'Steven']
['Valerie', 'Steven']


##### Set/Dict Comprehension

In [183]:
# Create a set based on lengths of words

strings = ['a', 'as', 'bat', 'car', 'dove']
unique_lengths = {len(x) for x in strings}
print(unique_lengths)

{1, 2, 3, 4}


In [185]:
# Create a location mapping a dictionary
strings = ['a', 'as', 'bat', 'car', 'dove']
loc_mapping = {val : index for index, val in enumerate(strings)}
print(loc_mapping)

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4}


### Functions

In [194]:
# Note, all functions in Python are represented as objects
# So we can pass in a list of functions to to other functions like this:

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result

strs = ['Alice', 'Bob  ', 'charlie']
clean_ops = [str.strip, str.upper]

print(clean_strings(strs, clean_ops))

['ALICE', 'BOB', 'CHARLIE']


#### Map

In [197]:
# Applies a function to a sequence of some kind

strs = ['Alice', 'Bob  ', 'charlie']

for string in map(str.upper, strs):
    print(string)

ALICE
BOB  
CHARLIE


#### Lambda Functions

In [204]:
# Lambda functions are the Python version of anonymous functions

def short(x):
    return x*2

lambda_short = lambda x: x*2

In [205]:
# Another practical example

def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 2,6]
apply_to_list(ints, lambda x: x*2)

[8, 0, 2, 4, 12]

#### Generators

In [207]:
# Python features an iterator protocol, a generic way to make objects iterable
# e.g. iterating over a dict yields the dict keys

some_dict = {'a':1, 'b':2, 'c':3}
for key in some_dict:
    print(key)

a
b
c


In [215]:
# This can be called directly using the 'iter' keyword

some_dict = {'a':1, 'b':2, 'c':3}

dict_iterator = iter(some_dict)

# Can pass into methods expecting a list or list-like object

print(list(dict_iterator))
# print(max(dict_iterator))

['a', 'b', 'c']


#### Generators

In [216]:
# A generator is a concise way to construct a new iterable object
# Generator returns multiple results lazily, pausing until next is requested
# Use the 'yield' keyword instead of 'return' to create a generator

def squares(n=10):
    for i in range(1, n+1):
        yield i ** 2

gen = squares()
gen

<generator object squares at 0x122978570>

In [217]:
# Gets evaluated when you iterate over it

for x in gen:
    print(x, end= ' ')

1 4 9 16 25 36 49 64 81 100 

In [220]:
# Can also use an expression to make generators more concise (similar to list comp)

gen = [x ** 2 for x in range(10)]
for x in gen:
    print(x, end= ' ')

0 1 4 9 16 25 36 49 64 81 

In [221]:
# Can use generators in place of list comprehensions 

sum(x ** 2 for x in range(100))

328350

In [232]:
# Lots of useful generators in itertools here
# https://docs.python.org/3/library/itertools.html

# A couple demonstrated:

In [231]:
# Don't forget to import itertools!
import itertools as it

# Combinations

ex_set = {1, 2, 6, 3, 135,6, 6231, 6, 4}
list(it.combinations(ex_set, 2))

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 6),
 (1, 135),
 (1, 6231),
 (2, 3),
 (2, 4),
 (2, 6),
 (2, 135),
 (2, 6231),
 (3, 4),
 (3, 6),
 (3, 135),
 (3, 6231),
 (4, 6),
 (4, 135),
 (4, 6231),
 (6, 135),
 (6, 6231),
 (135, 6231)]

In [235]:
# Permutations
import itertools as it

ex_set = {1, 2, 6, 3, 135,6, 6231, 6, 4}
list(it.permutations(ex_set, 2))

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 6),
 (1, 135),
 (1, 6231),
 (2, 1),
 (2, 3),
 (2, 4),
 (2, 6),
 (2, 135),
 (2, 6231),
 (3, 1),
 (3, 2),
 (3, 4),
 (3, 6),
 (3, 135),
 (3, 6231),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 6),
 (4, 135),
 (4, 6231),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 135),
 (6, 6231),
 (135, 1),
 (135, 2),
 (135, 3),
 (135, 4),
 (135, 6),
 (135, 6231),
 (6231, 1),
 (6231, 2),
 (6231, 3),
 (6231, 4),
 (6231, 6),
 (6231, 135)]

### Files and the Operating System

In [257]:
path = './crushp.txt'

lines = [line for line in open(path)]
lines

['This is an example text file\n',
 'I am practicing my VIM skills\n',
 'I am practicing my VIM skills\n',
 'I am practicing my VIM skillz\n']

In [258]:
# Can access by line as with an array

lines[0]

'This is an example text file\n'

In [263]:
# Very important! Like C, must remember to close files or there will be memory leaks

path = './crushp.txt'

f = open(path)
f.close()

In [282]:
# Can also use the "with" statement to close a file at the end of the block

path = './crushp.txt'
lines = [];

with open(path) as f:
    lines = [line for line in open(path)]
print(lines)

print(f.closed)

['This is an example text file\n', 'I am practicing my VIM skills\n', 'I am practicing my VIM skills\n', 'I am practicing my VIM skillz\n']
True


In [288]:
# Alternative way to read lines into a file

path = './crushp.txt'
lines = [];

with open(path) as f:
    lines = f.readlines()
print(lines)

print(f.closed)

['This is an example text file\n', 'I am practicing my VIM skills\n', 'I am practicing my VIM skills\n', 'I am practicing my VIM skillz\n']
True


In [287]:
# Use 'read' and 'write' methods just like you would in C

path = './crushp.txt'

f = open(path)
f.read(10)

# Goto a specific character in the file (by integer)
f.seek(10)

# Where are you in the file?
f.tell()

# close the file
f.close()

f.closed

True

## NumPy

### Introduction to the NumPy Array

#### ndarray objects are the basis of NumPy computing

In [294]:
# Creates a matrix of dimensions x,y with values selected at random from a standard norm dist.

np.random.randn(2,3)

array([[-0.10043225,  0.69225456, -0.5355994 ],
       [-1.17543133, -0.53292317, -0.31573878]])

In [383]:
# A few other ways to initialize a matrix

# Initialize each value in a row to the same value

arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

print(arr)
print('\n')
    
    
# Initialize sequentially

arr2 = np.arange(32).reshape(8,4)
print(arr2)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [297]:
# Can do scalar or vector operations

data = np.random.randn(2,3)
print(data)
print(data * 10)
print(data + data)

[[-0.63863108 -1.14957662 -1.68275552]
 [-0.44124116  1.74118678  0.88941171]]
[[ -6.38631084 -11.49576625 -16.82755515]
 [ -4.41241159  17.41186784   8.89411708]]
[[-1.27726217 -2.29915325 -3.36551103]
 [-0.88248232  3.48237357  1.77882342]]


In [302]:
# Note, an ndarray is a generic multi-dim container for data that is all the same type

data = np.random.randn(2,3)

print(data.shape)
print(data.dtype)

(2, 3)
float64


In [305]:
# Numpy equivalent of range function: arange

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [309]:
# can initialize to zeroes or ones

print(np.ones(10))
print(np.zeros(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [310]:
# Can also initialize empty matrices using .empty (note, could contain garbage values)

np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [317]:
# Can also create an identity matrix

print(np.eye(3,3))
print('\n')
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### NumPy Operations using matrices/ndarrays

In [327]:
arr = np.array([[1,2,3],[4,5,6]])

# Basic Array

print(arr)
print("\n")

# Arithmetic ops apply element-wise (b/n equal size arrays):

print(arr + arr)
print("\n")

[[1 2 3]
 [4 5 6]]


[[ 2  4  6]
 [ 8 10 12]]




In [329]:
# Scalar ops apply to each element in the array

arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print("\n")

print(3* arr)

[[1 2 3]
 [4 5 6]]


[[ 3  6  9]
 [12 15 18]]


In [332]:
# Can evaluate boolean expressions too (element-wise)

arr = np.array([[1,2,3],[4,5,6]])

arr1 = np.array([[4,1,4],[1,1,10]])

arr < arr1

array([[ True, False,  True],
       [False, False,  True]])

#### NumPy Indexing / Slicing

In [337]:
# Can use the colon to slice an array. Note that it is includes start index value
# But it excludes the end

arr = np.arange(10)
print(arr)
print(arr[5:8])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]


In [341]:
# Note: indexing in NumPy always returns a view on the ndarray object

arr = np.arange(10)

arr_slice = arr[5:8]
arr_slice[0] = 12345

# fifth index in original array should be changed
print(arr)
print(arr_slice)


[    0     1     2     3     4 12345     6     7     8     9]
[12345     6     7]


In [342]:
# Must use the copy() method to avoid that behavior

arr = np.arange(10)

arr_slice = arr[5:8].copy()
arr_slice[0] = 12345

# Original array is preserved
print(arr)
print(arr_slice)

[0 1 2 3 4 5 6 7 8 9]
[12345     6     7]


In [345]:
# Accessing a 2d array (think of the first number as rows and second number as cols)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[0,2]

3

In [346]:
# Slice a 2d array 

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [349]:
#3d arrays: if you omit a dimensional index when selecting, it returns a new ndarray
# with all the data from higher dimensions

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [354]:
# Both scalars and vectors can be assigned 

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
newNum = 36
old_values = arr3d[0].copy()

arr3d[0] = newNum
print(arr3d)
print('\n')

arr3d[0] = old_values
print(arr3d)

[[[36 36 36]
  [36 36 36]]

 [[ 7  8  9]
  [10 11 12]]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Boolean Indexing

In [368]:
# Important Note: selecting an array by Boolean indexing ALWAYS creates a copy of the data

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [365]:
# Can pass in the result of a boolean array as a "mask" for indexing another array
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7,3)
print(data)
print('\n')
print(data[names == 'Bob'])

[[ 0.99084072 -0.60752412 -0.796238  ]
 [ 2.72541825 -1.78651605 -0.6950912 ]
 [-1.09726259 -1.54522844 -0.57216675]
 [-0.08135472  1.89829076  0.09524627]
 [-0.2965087   0.98917649 -0.79331886]
 [-1.94335315  1.87656709 -0.51921007]
 [ 0.15295558  1.20891556  2.01263155]]


[[ 0.99084072 -0.60752412 -0.796238  ]
 [-0.08135472  1.89829076  0.09524627]]


In [366]:
# Can also select everything EXCEPT a certain value by using either != or ~
# != for not equal, or ~ to invert the general condition

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7,3)
print(data)
print('\n')
print(data[~(names == 'Bob')])

[[-0.9854209   0.54912374  0.29987391]
 [-0.19152763  1.11921547 -0.53233628]
 [ 0.20190788  0.04989617  0.06173659]
 [-1.04175282 -1.32179931  0.21208548]
 [ 0.48457484 -0.73380653 -0.62347106]
 [ 0.36791838  0.07333937  1.14508697]
 [-1.01007257 -0.43941541  0.72437116]]


[[-0.19152763  1.11921547 -0.53233628]
 [ 0.20190788  0.04989617  0.06173659]
 [ 0.48457484 -0.73380653 -0.62347106]
 [ 0.36791838  0.07333937  1.14508697]
 [-1.01007257 -0.43941541  0.72437116]]


In [367]:
# Can combine multiple boolean conditions 

mask = (names == 'Bob') | (names == 'Will')

data = np.random.randn(7,3)
print(data)
print('\n')
print(data[mask])

[[-0.38197504  0.17667401 -0.19144414]
 [-1.20548899 -0.08147095  0.46775268]
 [ 0.88229245  2.06523931 -0.32767379]
 [-1.28403643 -0.48097696  1.39069072]
 [-1.53641005 -0.02794774  1.42355056]
 [-0.35192579  1.01652372  0.6042608 ]
 [-0.80301198 -1.44056848 -0.65622103]]


[[-0.38197504  0.17667401 -0.19144414]
 [ 0.88229245  2.06523931 -0.32767379]
 [-1.28403643 -0.48097696  1.39069072]
 [-1.53641005 -0.02794774  1.42355056]]


In [370]:
# Boolean indexing enables setting values in a common-sense way

data = np.random.randn(7,3)

print(data)
print ('\n')
data[data < 0] = 0
print(data)

[[ 0.80358771  0.69535344 -2.75945358]
 [ 0.91022337 -0.75128288 -0.05847357]
 [-0.35086914  0.7443502   2.23612539]
 [-0.55913406 -0.06505146 -1.26442435]
 [-0.0769116  -0.06932083  1.58886348]
 [-0.8599373  -0.14004944 -0.76572048]
 [ 0.25006579  0.13833722 -0.82304148]]


[[0.80358771 0.69535344 0.        ]
 [0.91022337 0.         0.        ]
 [0.         0.7443502  2.23612539]
 [0.         0.         0.        ]
 [0.         0.         1.58886348]
 [0.         0.         0.        ]
 [0.25006579 0.13833722 0.        ]]


In [388]:
# Can also pass in an array as index to access specific rows

arr = np.arange(32).reshape(8,4)
print(arr)
print('\n')

print(arr[[1,2,3]])
print('\n')

# Negative indices count backwards

print(arr[[-1,-2,-3]])
print('\n')

# Can also select specific elements vector-wise by passing in two arrays

print(arr[[1,2,3],[1,2,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[28 29 30 31]
 [24 25 26 27]
 [20 21 22 23]]


[ 5 10 15]


In [394]:
# Transposing matrices

arr = np.arange(32).reshape(8,4)

print(arr)
print('\n')

# Attribute access
print(arr.T)
print('\n')

# Method access 
print(arr.transpose())


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [397]:
# For higher dimensional arrays, pass in a tuple of axes to transmute the axes around

arr = np.arange(16).reshape(2,2,4)
print(arr)
print('\n')

# Swap first and second axes and leave third unchanged
print(arr.transpose((1, 0, 2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [400]:
# Can also do this by using swapaxes()

arr = np.arange(16).reshape(2,2,4)
print(arr)
print('\n')

# Swap second and third axes and leave first unchanged
print(arr.swapaxes(1,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### Universal Functions

#### Vectorized wrappers for simple functions that take scalar values and produce one or more scalar results

In [416]:
import math

# Example: square roots

# broke
arr = list(range(10))
for i in arr:
    arr[i] = math.sqrt(i)
print(arr)
print('\n')

# woke
arr2 = np.arange(10)
print(np.sqrt(arr2))

[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0]


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [423]:
# Unary univesral function takes one array:

arr = np.arange(10)
print(np.exp(arr))
print('\n')

# Binary universal function take two arrays:

x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
print('\n Maximum comparing elements pair-wise')
print(np.maximum(x,y))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


[ 0.58225565  1.1257346  -0.27893688  0.77840517  0.66229671 -0.95171185
  0.79958818  0.17165157]
[-0.63171973 -0.76051086  0.84807148  0.62406641  0.57395124  0.33416186
  0.83924917  0.83837584]

 Maximum comparing elements pair-wise
[0.58225565 1.1257346  0.84807148 0.77840517 0.66229671 0.33416186
 0.83924917 0.83837584]


In [426]:
# Some unary functions return multiple arrays, like modf which returns a whole number
# and the mantissa separately

arr = np.random.randn(10)
print(arr)
print('\n')

remainder, whole = np.modf(arr)
print(whole)
print(remainder)


[ 0.80150711  1.26671598 -0.16518253 -0.44732526  0.75077277  0.56723895
  0.09823023  0.83160117 -0.02592507  1.5583892 ]


[ 0.  1. -0. -0.  0.  0.  0.  0. -0.  1.]
[ 0.80150711  0.26671598 -0.16518253 -0.44732526  0.75077277  0.56723895
  0.09823023  0.83160117 -0.02592507  0.5583892 ]


In [429]:
# Can also modify the array inplace by passing in the optional "out" argument as below

arr = np.random.randn(10)
np.square(arr, arr)

array([4.55174727e-01, 3.93046376e+00, 6.48962120e-02, 3.56051667e+00,
       3.50404068e-01, 2.53101898e-01, 1.86756487e-01, 1.68665258e+00,
       2.61721727e-01, 4.05655023e-05])

In [436]:
# Couple of other cool ufuncs:

## Unary

arr = np.random.randn(10)

### Absolute Value
np.abs(arr)

### Sign
np.sign(arr)

### Ceiling/Floor
np.ceil(arr)
np.floor(arr)

### Round to nearest integer, preserving dtype
np.rint(arr)

array([ 0., -1.,  1.,  0., -1., -0., -0., -1.,  1., -2.])

In [441]:
## Binary

x = np.random.randn(10)
y = np.random.randn(10)

### All normal ops
np.add(x,y)

### Floor divide truncates remainder
np.floor_divide(x,y)

### Raise elements in first array to power in second array
np.power(x,y)

### Find maximum ignoring nans
np.fmax(np.power(x,y), x)

### Copy sign from first to second array
np.copysign(x,y)

/Users/alex/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in power
  del sys.path[0]
/Users/alex/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in power
  app.launch_new_instance()


array([-0.61722456,  1.974543  , -0.69686473,  1.52165657, -1.59158564,
        0.9231509 ,  1.25615265, -1.07470089, -1.13655436,  0.16628311])

## Array Oriented Programming with Arrays